### ISSUE TITLE
Unexpected value 'MnFullpageDirective' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by StasGoshtein** [meiblorn/ngx-fullpage#142]
Just trying to add your code, as written in docs.
After adding to declarations, although webpack compiles the code, the following error appears in the console:

compiler.umd.js?9df7:14374Uncaught Error: Unexpected value 'MnFullpageDirective' declared by the module 'AppModule'
    at eval (eval at <anonymous> (http://localhost:8080/vendor.js:94:2), <anonymous>:14374:33)
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (eval at <anonymous> (http://localhost:8080/vendor.js:94:2), <anonymous>:14361:51)
    at RuntimeCompiler._compileComponents (eval at <anonymous> (http://localhost:8080/vendor.js:94:2), <anonymous>:17063:49)
    at RuntimeCompiler._compileModuleAndComponents (eval at <anonymous> (http://localhost:8080/vendor.js:94:2), <anonymous>:17001:39)
    at RuntimeCompiler.compileModuleAsync (eval at <anonymous> (http://localhost:8080/vendor.js:94:2), <anonymous>:16992:23)
    at PlatformRef_._bootstrapModuleWithZone (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:6684:29)
    at PlatformRef_.bootstrapModule (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:6666:25)
    at Object.eval (eval at <anonymous> (http://localhost:8080/app.js:87:2), <anonymous>:9:53)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:87:2), <anonymous>:11:30)
    at Object.<anonymous> (http://localhost:8080/app.js:87:2)
    at __webpack_require__ (http://localhost:8080/polyfills.js:51:30)
    at Object.<anonymous> (http://localhost:8080/app.js:6:19)
    at __webpack_require__ (http://localhost:8080/polyfills.js:51:30)
    at webpackJsonpCallback (http://localhost:8080/polyfills.js:22:20)
    at http://localhost:8080/app.js:1:1

**Comment by kmoroe22** [comment]
@StasGoshtein Same issue here @meiblorn 

Happy to help wherever I can

**Comment by mauricio1990silva** [comment]
any update on this one? I am facing the same issue

**Comment by tiberiumihai** [comment]
Any updates on this one? I've read every single thread on the web for:
Unexpected value '<something>' declared by the module 'AppModule'.

Using webpack 1.13.3 and after update to webpack v2 I got the same error in console.

**Comment by edoura** [comment]
same issue

**Comment by misterzik** [comment]
any solutions on this one?

**Comment by StanFaas** [comment]
Did anyone already has this one fixed?

**Comment by aalleard** [comment]
Hello, same issue here, after update from Angular 2.4.1 to 2.4.7. Any advice?

**Comment by meiblorn** [comment]
Updated to the new version. Closing.
