### ISSUE TITLE
Unexpected value 'MnFullpageDirective' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation

### ISSUE THREAD

**Issue by codeuniquely** [meiblorn/ngx-fullpage#426]
Followed the first example given at https://www.npmjs.com/package/ng2-fullpage

The only difference is that because I only just installed angular2 so my package.json file has V4 

```
"dependencies": {
    "@angular/animations": "^4.2.2",
    "@angular/common": "^4.2.2",
    "@angular/compiler": "^4.2.2",
    "@angular/core": "^4.2.2",
    "@angular/forms": "^4.2.2",
    "@angular/http": "^4.2.2",
    "@angular/platform-browser": "^4.2.2",
    "@angular/platform-browser-dynamic": "^4.2.2",
    "@angular/router": "^4.2.2",
    "core-js": "^2.4.1",
    "ng2-fullpage": "^2.1.0",
    "rxjs": "^5.4.0",
    "zone.js": "^0.8.12"
  },
```

The default project compiles OK and shows the home page - as expected 

When I put in the additional lines as recommend on your NPM page then the code also compiles OK and webpack starts, but at runtime - I'm getting this console error ....

and only the default "Loading ..." renders

```
compiler.es5.js:1917 Uncaught Error: Unexpected value 'MnFullpageDirective' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (webpack:///../~/@angular/compiler/@angular/compiler.es5.js?:1917:34)
    at eval (webpack:///../~/@angular/compiler/@angular/compiler.es5.js?:15649:40)
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (webpack:///../~/@angular/compiler/@angular/compiler.es5.js?:15631:54)
    at JitCompiler._loadModules (webpack:///../~/@angular/compiler/@angular/compiler.es5.js?:26908:70)
    at JitCompiler._compileModuleAndComponents (webpack:///../~/@angular/compiler/@angular/compiler.es5.js?:26881:36)
    at JitCompiler.compileModuleAsync (webpack:///../~/@angular/compiler/@angular/compiler.es5.js?:26810:37)
    at PlatformRef_._bootstrapModuleWithZone (webpack:///../~/@angular/core/@angular/core.es5.js?:4799:25)
    at PlatformRef_.bootstrapModule (webpack:///../~/@angular/core/@angular/core.es5.js?:4785:21)
    at Object.eval (webpack:///./main.ts?:10:53)
    at eval (webpack:///./main.ts?:12:30)
    at Object.298 (http://localhost:3000/app.js:510:1)
    at __webpack_require__ (http://localhost:3000/polyfill.js:55:30)
    at eval (webpack:///multi_../~/webpack-dev-server/client?:2:18)
    at Object.807 (http://localhost:3000/app.js:833:1)
    at __webpack_require__ (http://localhost:3000/polyfill.js:55:30)
    at webpackJsonpCallback (http://localhost:3000/polyfill.js:26:23)
    at http://localhost:3000/app.js:1:1
```

**Comment by codeuniquely** [comment]
I solved this by by making sure the WEBPACK.config.js file had the following

```
resolve: {
    extensions: ['.ts', '.js'],
    modules: [
      path.resolve( __dirname ),
      path.resolve( __dirname, 'node_modules' )
    ],
    alias:{  }
  },
```
